tabuleria_luderia/Controllers/LojasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using tabuleria_luderia.Models;

namespace tabuleria_luderia.Controllers
{
    [Authorize]
    public class LojasController : Controller
    {
        private readonly AddDbContext _context;

        public LojasController(AddDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var dados = await _context.Lojas.ToListAsync();

            return View(dados);

        }

        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create(Loja loja)
        {

            if (ModelState.IsValid)
            {
                _context.Lojas.Add(loja);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(loja);

        }

        public async Task<IActionResult> Edit(int? id) 
        {
           if (id == null)
            return NotFound();

            var dados = await _context.Lojas.FindAsync(id);
            if (dados == null)
                return NotFound();
            
            return View(dados);   
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Loja loja)
        {
            if (id != loja.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Lojas.Update(loja);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            
            return View();
        }
        public async Task<IActionResult> Details(int? id) 
        {
            if(id == null)
                return NotFound();
            
            var dados = await _context.Lojas.FindAsync(id);

            if(dados == null)
                return NotFound();

            return View(dados);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Lojas.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Lojas.FindAsync(id);

            if (dados == null)
                return NotFound();

            _context.Lojas.Remove(dados);
            await _context.SaveChangesAsync();

            return View(dados);
        }

        public async Task<IActionResult> Relatorio(int? id)
        {

            if (id == null)
                return NotFound();

            var loja = await _context.Lojas.FindAsync(id);

            if(loja == null)
                return NotFound();

            var jogos = await _context.Jogos
                .Where(c => c.LojaId == id)
                .OrderByDescending(c => c.NomeDoJogo)
                .ToListAsync();

            decimal total = jogos.Sum(c => c.Valor);


            ViewBag.Loja = loja;    
            ViewBag.Total = total;  


            return View(jogos);
        }
    }

}

tabuleria_luderia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tabuleria_luderia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tabuleria_luderia.styles.css" asp-append-version="true" />
    <style>
      
      
        footer {
            background-color:#FFC3C3;
            padding: 15px;
            bottom: 0;
            position: fixed;
            width: 100%;
            text-align: center;
         
        }
    </style>
</head>


<body>
    <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 heading" id="cabecalho" style=" background: #FFC3C3;">
                <div class="container-fluid" style=" background: #FFC3C3; top: 0;">
                    
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://i.postimg.cc/Bb2zp0VV/Logo.png" ></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Index">Lojas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Jogos" asp-action="Index">Jogos</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a>
                                </li>
                                    
                            }
                        }
                        
                       
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                Olá, @User.Identity.Name <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>
                            </li>
                        }
                        
                       
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
                <b>&copy; 2023 - tabuleria_luderia - Desenvolvido por A & A  | </b><a asp-area="" asp-controller="Home" asp-action="Privacy"><b>Privacidade </b> </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>